- name: Ensure Docker is installed
  hosts: all
  become: true

  tasks:
    - name: Define Docker version variable
      command: which docker
      register: docker_path
      ignore_errors: true

    - name: Check Docker version if installed
      command: "{{ docker_path.stdout }} --version"
      register: docker_version
      when: docker_path.stdout != ""
      ignore_errors: true

    - name: Output Docker version if installed
      debug:
        msg: "Docker is already installed. Version: {{ docker_version.stdout }}"
      when: docker_path.stdout != "" and docker_version.rc != 0

    - name: Install Docker if not installed
      block:
        - name: Update and upgrade the system
          apt:
            update_cache: true
            cache_valid_time: 3600

        - name: Install required packages
          apt:
            name:
              - apt-transport-https
              - ca-certificates
              - curl
              - software-properties-common
            state: present

        - name: Add Docker GPG key
          apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present

        - name: Add Docker repository
          apt_repository:
            repo: >-
              deb [arch={{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' }}]
              https://download.docker.com/linux/{{ ansible_distribution | lower }}
              {{ ansible_lsb.codename | default(ansible_distribution_release) }} stable
            state: present

        - name: Install Docker
          apt:
            name: docker-ce
            state: present

        - name: Start and enable Docker service
          systemd:
            name: docker
            state: started
            enabled: true
      when: docker_path.stdout == ""
