name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: deploy
  cancel-in-progress: false

jobs:
  deploy:
    name: Docker Compose Deploy
    runs-on: mcp

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set .env.docker
        run: |
          cat << 'EOF' > .env.docker
          ${{ secrets.ENV }}
          EOF

      - name: Deploy with docker compose
        run: |
          docker compose up --build -d --remove-orphans