name: Housekeeping

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      days:
        description: 'Retention in days'
        required: false
        default: '30'
        type: string

permissions:
  actions: write

jobs:
  call-shared:
    uses: vilnius-vmsa/shared-workflows/.github/workflows/housekeeping.yml@main
    with:
      days: ${{ inputs.days }}
